### ISSUE TITLE
re: docs / usage 

### ISSUE THREAD

**Issue by mrgleeco** [futuresimple/helm-secrets#14]
hello - First: this is great! Thank you.

Reading & learning from your README, i wondered if it could be clearer.  Specifically, 

* `helm-wrapper` - what exactly is this referring to?  Is it part of this repo? Are you referring to `wrapper.sh` script here?  IS it part of `helm`? 

* what is the work flow for **using** `helm secrets`?  ie. how do i install a chart with a sops secret?  Does it do it automagically?  Do i need to decrypt first and store output?  A working example here would be nice.

With guidance, i'd love to submit a PR and improve this project.

**Comment by commandline** [comment]
I have exactly the same questions. So far, working with a secrets file as we would store it into our S3 backup makes sense and the editing experience is well covered. When I naively try to install the chart, though, then my cluster rejects it because it is obviously still reading the encrypted value.

**Comment by szibis** [comment]
Is this ok as the starting point?

https://github.com/futuresimple/helm-secrets/pull/15

**Comment by commandline** [comment]
Yeah, the examples for invoking the wrapper helped clarify what we were doing wrong, at least--thanks!

**Comment by szibis** [comment]
https://github.com/futuresimple/helm-secrets/pull/15 merged if you like to improve, #PR's welcome.
